/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "Init.h"
#include "FreeRTOS.h"
#include "task.h"

#define DWT_CTRL	(*(volatile uint32_t*)0xE0001000)

TaskHandle_t task1_handle;
TaskHandle_t task2_handle;
TaskHandle_t task3_handle;
TaskHandle_t task4_handle;
TaskHandle_t task5_handle;
TaskHandle_t task6_handle;
TaskHandle_t task7_handle;
TaskHandle_t task8_handle;

BaseType_t status;

uint8_t button_pressed;
uint8_t state = ON;

static void task1_handler(void *parameters)
{
	while(1)
	{
		Set_GPIO_Output((GPIOx_Reg_t*)GPIOD_ADDR, OUTPUT_SET, 12);
		button_pressed = GPIO_Pin_Read((GPIOx_Reg_t*)GPIOA_ADDR, 0);

		if(button_pressed == 1 && state == OFF)
		{
			state = ON;
			Enable_AHB1_Peri_Clk(GPIODEN, ENABLE);
			delay_ms(100);
		}
		else if(button_pressed == 1 && state == ON)
		{
			state = OFF;
			Enable_AHB1_Peri_Clk(GPIODEN, DISABLE);
			delay_ms(100);
		}

	}
}

static void task2_handler(void *parameters)
{
	while(1)
	{
		Set_GPIO_Output((GPIOx_Reg_t*)GPIOD_ADDR, OUTPUT_SET, 13);
	}
}

static void task3_handler(void *parameters)
{
	while(1)
	{
		Set_GPIO_Output((GPIOx_Reg_t*)GPIOD_ADDR, OUTPUT_SET, 14);
	}
}

static void task4_handler(void *parameters)
{
	while(1)
	{
		Set_GPIO_Output((GPIOx_Reg_t*)GPIOD_ADDR, OUTPUT_SET, 15);
	}
}

static void task5_handler(void *parameters)
{
	while(1)
	{
		Set_GPIO_Output((GPIOx_Reg_t*)GPIOD_ADDR, OUTPUT_RESET, 12);
	}
}

static void task6_handler(void *parameters)
{
	while(1)
	{
		Set_GPIO_Output((GPIOx_Reg_t*)GPIOD_ADDR, OUTPUT_RESET, 13);
	}
}

static void task7_handler(void *parameters)
{
	while(1)
	{
		Set_GPIO_Output((GPIOx_Reg_t*)GPIOD_ADDR, OUTPUT_RESET, 14);
	}
}

static void task8_handler(void *parameters)
{
	while(1)
	{
		Set_GPIO_Output((GPIOx_Reg_t*)GPIOD_ADDR, OUTPUT_RESET, 15);
	}
}

int main(void)
{
 	Init();

	//Enable the CYCNT Counter
	DWT_CTRL |= (1<<0);

	SEGGER_SYSVIEW_Conf();

	SEGGER_SYSVIEW_Start();

	status = xTaskCreate(task1_handler, "Task-1", 200, "Hello world from Task-1", 2, &task1_handle);
	
	configASSERT(status == pdPASS);

	status = xTaskCreate(task2_handler, "Task-2", 200, "Hello world from Task-2", 2, &task2_handle);
	
	configASSERT(status == pdPASS);

	status = xTaskCreate(task3_handler, "Task-3", 200, "Hello world from Task-3", 2, &task3_handle);
	
	configASSERT(status == pdPASS);

	status = xTaskCreate(task4_handler, "Task-4", 200, "Hello world from Task-4", 2, &task4_handle);
	
	configASSERT(status == pdPASS);

	status = xTaskCreate(task5_handler, "Task-5", 200, "Hello world from Task-1", 2, &task5_handle);
	
	configASSERT(status == pdPASS);

	status = xTaskCreate(task6_handler, "Task-6", 200, "Hello world from Task-2", 2, &task6_handle);
	
	configASSERT(status == pdPASS);

	status = xTaskCreate(task7_handler, "Task-7", 200, "Hello world from Task-3", 2, &task7_handle);
	
	configASSERT(status == pdPASS);

	status = xTaskCreate(task8_handler, "Task-8", 200, "Hello world from Task-4", 2, &task8_handle);
	
	configASSERT(status == pdPASS);

	//Start the FreeRTOS scheduler
	vTaskStartScheduler();


	while(1)
	{

	}

	return 0;
}
