/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "Init.h"

uint8_t data[5] = {1,2,3,4,5};
uint8_t cnt = 0;

int main(void)
{
 	Init();

	LCD_Init_4Bit_Interface();

	
	while(1)
	{
		cnt++;
		if(cnt > 100) cnt = 0;
		Cal_SDcard_Usage(cnt%10, cnt/10, cnt);
		LED_Blink();
	}


	return 0;
}
