/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "Init.h"

uint8_t data[5] = {1,2,3,4,5};

int main(void)
{
 	Init();

	I2C_Send_Master_To_Slave((I2Cx_Reg_t*)I2C1_ADDR, 0x27, data, sizeof(data));

	while(1)
	{
		Set_GPIO_Output((GPIOx_Reg_t*)GPIOD_ADDR, OUTPUT_SET, 12);
		delay_ms(500);
		Set_GPIO_Output((GPIOx_Reg_t*)GPIOD_ADDR, OUTPUT_RESET, 12);
		delay_ms(500);
	}


	return 0;
}
